#spring:
#  datasource:
#    master:
#      # 驱动类
#      driver-class-name: com.mysql.jdbc.Driver
#      # 主数据库服务器用户名
#      username: root
#      # 主数据库服务器密码
#      password:
#      # 主数据库服务器用户名，到时候更换自己的ip端口
#      jdbc-url: jdbc:mysql://localhost:3316/db?characterEncoding=utf-8
#      # 从数据库服务器配置
#    slave1:
#      # 从数据库服务器用户名
#      username: root
#      # 从数据库服务器密码
#      password:
#      # 从数据库服务器url,到时候更换自己的ip端口
#      jdbc-url: jdbc:mysql://localhost:3326/db?characterEncoding=utf-8
#    slave2:
#      # 从数据库服务器用户名
#      username: root
#      # 从数据库服务器密码
#      password:
#      # 从数据库服务器url,到时候更换自己的ip端口
#      jdbc-url: jdbc:mysql://localhost:3336/db?characterEncoding=utf-8
#  profiles:
#    active: master-slave
#  shardingsphere:
#    props:
#      sql:
#        show: true



#logging:
#  level:
#    com.readwite.application: debug